//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examen()
        {
            this.PuntajePreguntas = new HashSet<PuntajePregunta>();
        }
    
        public int IdExamen { get; set; }
        public string nombreExamen { get; set; }
        public System.DateTime fecha { get; set; }
        public int preguntasResueltas { get; set; }
        public int avance { get; set; }
        public int alumnoIdAlumno { get; set; }
        public int numeroDePreguntas { get; set; }
        public bool banderaAleatorio { get; set; }
        public bool banderaCronometro { get; set; }
        public bool banderaGuardar { get; set; }
        public bool banderaReanudar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntajePregunta> PuntajePreguntas { get; set; }
    }
}
