//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntajePregunta
    {
        public int IdPuntajePreguntas { get; set; }
        public int ExamenIdExamen { get; set; }
        public string sp1 { get; set; }
        public string sp2 { get; set; }
        public string sp3 { get; set; }
        public string sp4 { get; set; }
        public string sp5 { get; set; }
        public string numeroDePregunta { get; set; }
    }
}
